name: flutter_explorer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.3

  fast_immutable_collections: ^7.0.3

  freezed_annotation: ^1.1.0

  get_it: ^7.2.0
  injectable: ^1.5.0

  provider: ^6.0.1
  flutter_bloc: ^7.3.1
  flutter_hooks: ^0.18.1
  flutter_hooks_bloc: ^0.16.0
  vrouter: ^1.2.0+15

  path: ^1.8.1
  path_provider: ^2.0.8
  watcher: ^1.0.1
  file_selector: ^0.8.2+1
  file_selector_windows: ^0.0.2+1

  flutter_treeview:
    path: treeview/

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_lints: ^1.0.4

  build_runner: ^2.1.7
  freezed: ^1.1.0
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true
